language: rust

matrix:
  include:
    -
      rust: stable
      script:
        - cargo build --verbose --release;
        - cargo test --verbose
        - sha256sum target/release/ptgrep > target/release/ptgrep.sha256
    -
      rust: beta
    -
      rust: nightly
  allow_failures:
    -
      rust: nightly
  fast_finish: true

cache: cargo

deploy:
  provider: releases
  api_key:
    secure: "C3THb5MOTgBNeJXaLQjKOGXKpJnvJeZluLmTKHRVmGMzCF8zcnz7DCV9VygBLzvtrxIge6hsI8xcoKJsDa9dnF4hffUVRApFDLUUx87HMljcmpQ7b0mR/nvsucR7MNswLnSGfhSjiaUqsl4GMbuTaJZR7NJJGunLsn0y1DzOsxG5JYXVrF5Xo8tTeWSQ7QWTtp1z4zrrlbwbpcec6TotNyAfinU5ZVUu3gQ4KT823K6Qc3VN4B/9f4qomM9BeFrEJp3sd+b67DteiSvMKm/q1i71Zi3mOm+1MCa7EpGZwFkkrOAr0Z1ISW4bzQ8gRRM1cwyDogXYfK8gMXPAMNqt8ODNcKBlVZdTHWHbrtL3HKjr0lsEGcexZoCOxlIti1T1ud/8/mfcyISjZxzrWFXlI3Ge1NrjOJzdHiVcWXYmTcwR7indTYzSxVlkDrKmlmFsFuEI9SimePaU2lTVAGi1EI2Ho0nLMDd+og40ttHoIEo5q8DJyUl7EqASetS+7vHBB7uUiWxFAEg1F/ab7sRqu43BXCG+5Z1UWZqpSOodDRxSFmatttogGvOAi3u8pDSuAOdYu5CiqWx/YEoOG8957WlZMrNyEfdk9W03o4QuWffTu9WlfkyaluzN6jxs1X8sOWE1q42tco7qtKGzcntZ2mGiwYvVqAqvjcoNrEwd8cQ="
  file:
    - target/release/ptgrep
    - target/release/ptgrep.sha256
  skip_cleanup: true
  on:
    tags: true

